var mongoose = require('mongoose');
var uniqueValidator = require('mongoose-unique-validator');

var Schema = mongoose.Schema;

var darwinCoreSchema = new Schema({
    registro: { type: String, required: false },
    // Record-Level
    type: { type: String, required: false, default: 'Sin especificar' },
    modified: { type: String, required: false, default: 'Sin especificar' },
    language: { type: String, required: false, default: 'Sin especificar' },
    license: { type: String, required: false, default: 'Sin especificar' },
    rightsHolder: { type: String, required: false, default: 'Sin especificar' },
    accessRights: { type: String, required: false, default: 'Sin especificar' },
    bibliographicCitation: { type: String, required: false, default: 'Sin especificar' },
    references: { type: String, required: false, default: 'Sin especificar' },
    institutionID: { type: String, required: false, default: 'Sin especificar' },
    collectionID: { type: String, required: false, default: 'Sin especificar' },
    datasetID: { type: String, required: false, default: 'Sin especificar' },
    institutionCode: { type: String, required: false, default: 'Sin especificar' },
    collectionCode: { type: String, required: false, default: 'Sin especificar' },
    datasetName: { type: String, required: false, default: 'Sin especificar' },
    ownerInstitutionCode: { type: String, required: false, default: 'Sin especificar' },
    basisOfRecord: { type: String, required: false, default: 'Sin especificar' },
    informationWithheld: { type: String, required: false, default: 'Sin especificar' },
    dataGeneralizations: { type: String, required: false, default: 'Sin especificar' },
    dynamicProperties: { type: String, required: false, default: 'Sin especificar' },
    // Occurrence
    occurrenceID: { type: String, required: false, default: 'Sin especificar' },
    catalogNumber: { type: String, required: false, default: 'Sin especificar' },
    recordNumber: { type: String, required: false, default: 'Sin especificar' },
    recordedBy: { type: String, required: false, default: 'Sin especificar' },
    individualCount: { type: String, required: false, default: 'Sin especificar' },
    organismQuantity: { type: String, required: false, default: 'Sin especificar' },
    organismQuantityType: { type: String, required: false, default: 'Sin especificar' },
    sex: { type: String, required: false, default: 'Sin especificar' },
    lifeStage: { type: String, required: false, default: 'Sin especificar' },
    reproductiveCondition: { type: String, required: false, default: 'Sin especificar' },
    behavior: { type: String, required: false, default: 'Sin especificar' },
    establishmentMeans: { type: String, required: false, default: 'Sin especificar' },
    occurrenceStatus: { type: String, required: false, default: 'Sin especificar' },
    preparations: { type: String, required: false, default: 'Sin especificar' },
    disposition: { type: String, required: false, default: 'Sin especificar' },
    associatedMedia: { type: String, required: false, default: 'Sin especificar' },
    associatedReferences: { type: String, required: false, default: 'Sin especificar' },
    associatedSequences: { type: String, required: false, default: 'Sin especificar' },
    associatedTaxa: { type: String, required: false, default: 'Sin especificar' },
    otherCatalogNumbers: { type: String, required: false, default: 'Sin especificar' },
    occurrenceRemarks: { type: String, required: false, default: 'Sin especificar' },
    // Organism
    organismID: { type: String, required: false, default: 'Sin especificar' },
    organismName: { type: String, required: false, default: 'Sin especificar' },
    organismScope: { type: String, required: false, default: 'Sin especificar' },
    associatedOccurrences: { type: String, required: false, default: 'Sin especificar' },
    associatedOrganisms: { type: String, required: false, default: 'Sin especificar' },
    previousIdentifications: { type: String, required: false, default: 'Sin especificar' },
    organismRemarks: { type: String, required: false, default: 'Sin especificar' },
    // MaterialSample
    materialSampleID: { type: String, required: false, default: 'Sin especificar' },
    // Event
    eventID: { type: String, required: false, default: 'Sin especificar' },
    parentEventID: { type: String, required: false, default: 'Sin especificar' },
    fieldNumber: { type: String, required: false, default: 'Sin especificar' },
    eventDate: { type: String, required: false, default: 'Sin especificar' },
    eventTime: { type: String, required: false, default: 'Sin especificar' },
    startDayOfYear: { type: String, required: false, default: 'Sin especificar' },
    endDayOfYear: { type: String, required: false, default: 'Sin especificar' },
    year: { type: String, required: false, default: 'Sin especificar' },
    month: { type: String, required: false, default: 'Sin especificar' },
    day: { type: String, required: false, default: 'Sin especificar' },
    verbatimEventDate: { type: String, required: false, default: 'Sin especificar' },
    habitat: { type: String, required: false, default: 'Sin especificar' },
    samplingProtocol: { type: String, required: false, default: 'Sin especificar' },
    sampleSizeValue: { type: String, required: false, default: 'Sin especificar' },
    sampleSizeUnit: { type: String, required: false, default: 'Sin especificar' },
    samplingEffort: { type: String, required: false, default: 'Sin especificar' },
    fieldNotes: { type: String, required: false, default: 'Sin especificar' },
    eventRemarks: { type: String, required: false, default: 'Sin especificar' },
    // Location
    locationID: { type: String, required: false, default: 'Sin especificar' },
    higherGeographyID: { type: String, required: false, default: 'Sin especificar' },
    higherGeography: { type: String, required: false, default: 'Sin especificar' },
    continent: { type: String, required: false, default: 'Sin especificar' },
    waterBody: { type: String, required: false, default: 'Sin especificar' },
    islandGroup: { type: String, required: false, default: 'Sin especificar' },
    island: { type: String, required: false, default: 'Sin especificar' },
    country: { type: String, required: false, default: 'Sin especificar' },
    countryCode: { type: String, required: false, default: 'Sin especificar' },
    stateProvince: { type: String, required: false, default: 'Sin especificar' },
    county: { type: String, required: false, default: 'Sin especificar' },
    municipality: { type: String, required: false, default: 'Sin especificar' },
    locality: { type: String, required: false, default: 'Sin especificar' },
    verbatimLocality: { type: String, required: false, default: 'Sin especificar' },
    minimumElevationInMeters: { type: String, required: false, default: 'Sin especificar' },
    maximumElevationInMeters: { type: String, required: false, default: 'Sin especificar' },
    verbatimElevation: { type: String, required: false, default: 'Sin especificar' },
    minimumDepthInMeters: { type: String, required: false, default: 'Sin especificar' },
    maximumDepthInMeters: { type: String, required: false, default: 'Sin especificar' },
    verbatimDepth: { type: String, required: false, default: 'Sin especificar' },
    minimumDistanceAboveSurfaceInMeters: { type: String, required: false, default: 'Sin especificar' },
    maximumDistanceAboveSurfaceInMeters: { type: String, required: false, default: 'Sin especificar' },
    locationAccordingTo: { type: String, required: false, default: 'Sin especificar' },
    locationRemarks: { type: String, required: false, default: 'Sin especificar' },
    decimalLatitude: { type: String, required: false, default: 'Sin especificar' },
    decimalLongitude: { type: String, required: false, default: 'Sin especificar' },
    geodeticDatum: { type: String, required: false, default: 'Sin especificar' },
    coordinateUncertaintyInMeters: { type: String, required: false, default: 'Sin especificar' },
    coordinatePrecision: { type: String, required: false, default: 'Sin especificar' },
    pointRadiusSpatialFit: { type: String, required: false, default: 'Sin especificar' },
    verbatimCoordinates: { type: String, required: false, default: 'Sin especificar' },
    verbatimLatitude: { type: String, required: false, default: 'Sin especificar' },
    verbatimLongitude: { type: String, required: false, default: 'Sin especificar' },
    verbatimCoordinateSystem: { type: String, required: false, default: 'Sin especificar' },
    verbatimSRS: { type: String, required: false, default: 'Sin especificar' },
    footprintWKT: { type: String, required: false, default: 'Sin especificar' },
    footprintSRS: { type: String, required: false, default: 'Sin especificar' },
    footprintSpatialFit: { type: String, required: false, default: 'Sin especificar' },
    georeferencedBy: { type: String, required: false, default: 'Sin especificar' },
    georeferencedDate: { type: String, required: false, default: 'Sin especificar' },
    georeferenceProtocol: { type: String, required: false, default: 'Sin especificar' },
    georeferenceSources: { type: String, required: false, default: 'Sin especificar' },
    georeferenceVerificationStatus: { type: String, required: false, default: 'Sin especificar' },
    georeferenceRemarks: { type: String, required: false, default: 'Sin especificar' },
    // GeologicalContext
    geologicalContextID: { type: String, required: false, default: 'Sin especificar' },
    earliestEonOrLowestEonothem: { type: String, required: false, default: 'Sin especificar' },
    latestEonOrHighestEonothem: { type: String, required: false, default: 'Sin especificar' },
    earliestEraOrLowestErathem: { type: String, required: false, default: 'Sin especificar' },
    latestEraOrHighestErathem: { type: String, required: false, default: 'Sin especificar' },
    earliestPeriodOrLowestSystem: { type: String, required: false, default: 'Sin especificar' },
    latestPeriodOrHighestSystem: { type: String, required: false, default: 'Sin especificar' },
    earliestEpochOrLowestSeries: { type: String, required: false, default: 'Sin especificar' },
    latestEpochOrHighestSeries: { type: String, required: false, default: 'Sin especificar' },
    earliestAgeOrLowestStage: { type: String, required: false, default: 'Sin especificar' },
    latestAgeOrHighestStage: { type: String, required: false, default: 'Sin especificar' },
    lowestBiostratigraphicZone: { type: String, required: false, default: 'Sin especificar' },
    highestBiostratigraphicZone: { type: String, required: false, default: 'Sin especificar' },
    lithostratigraphicTerms: { type: String, required: false, default: 'Sin especificar' },
    group: { type: String, required: false, default: 'Sin especificar' },
    formation: { type: String, required: false, default: 'Sin especificar' },
    member: { type: String, required: false, default: 'Sin especificar' },
    bed: { type: String, required: false, default: 'Sin especificar' },
    // Identification
    identificationID: { type: String, required: false, default: 'Sin especificar' },
    identificationQualifier: { type: String, required: false, default: 'Sin especificar' },
    typeStatus: { type: String, required: false, default: 'Sin especificar' },
    identifiedBy: { type: String, required: false, default: 'Sin especificar' },
    dateIdentified: { type: String, required: false, default: 'Sin especificar' },
    identificationReferences: { type: String, required: false, default: 'Sin especificar' },
    identificationVerificationStatus: { type: String, required: false, default: 'Sin especificar' },
    identificationRemarks: { type: String, required: false, default: 'Sin especificar' },
    // Taxon
    taxonID: { type: String, required: false, default: 'Sin especificar' },
    scientificNameID: { type: String, required: false, default: 'Sin especificar' },
    acceptedNameUsageID: { type: String, required: false, default: 'Sin especificar' },
    parentNameUsageID: { type: String, required: false, default: 'Sin especificar' },
    originalNameUsageID: { type: String, required: false, default: 'Sin especificar' },
    nameAccordingToID: { type: String, required: false, default: 'Sin especificar' },
    namePublishedInID: { type: String, required: false, default: 'Sin especificar' },
    taxonConceptID: { type: String, required: false, default: 'Sin especificar' },
    scientificName: { type: String, required: false, default: 'Sin especificar' },
    acceptedNameUsage: { type: String, required: false, default: 'Sin especificar' },
    parentNameUsage: { type: String, required: false, default: 'Sin especificar' },
    originalNameUsage: { type: String, required: false, default: 'Sin especificar' },
    nameAccordingTo: { type: String, required: false, default: 'Sin especificar' },
    namePublishedIn: { type: String, required: false, default: 'Sin especificar' },
    namePublishedInYear: { type: String, required: false, default: 'Sin especificar' },
    higherClassification: { type: String, required: false, default: 'Sin especificar' },
    kingdom: { type: String, required: false, default: 'Sin especificar' },
    phylum: { type: String, required: false, default: 'Sin especificar' },
    _class: { type: String, required: false, default: 'Sin especificar' },
    order: { type: String, required: false, default: 'Sin especificar' },
    family: { type: String, required: false, default: 'Sin especificar' },
    genus: { type: String, required: false, default: 'Sin especificar' },
    subgenus: { type: String, required: false, default: 'Sin especificar' },
    specificEpithet: { type: String, required: false, default: 'Sin especificar' },
    infraspecificEpithet: { type: String, required: false, default: 'Sin especificar' },
    taxonRank: { type: String, required: false, default: 'Sin especificar' },
    verbatimTaxonRank: { type: String, required: false, default: 'Sin especificar' },
    scientificNameAuthorship: { type: String, required: false, default: 'Sin especificar' },
    vernacularName: { type: String, required: false, default: 'Sin especificar' },
    nomenclaturalCode: { type: String, required: false, default: 'Sin especificar' },
    taxonomicStatus: { type: String, required: false, default: 'Sin especificar' },
    nomenclaturalStatus: { type: String, required: false, default: 'Sin especificar' },
    taxonRemarks: { type: String, required: false, default: 'Sin especificar' },
    // MeasurementOrFact
    measurementID: { type: String, required: false, default: 'Sin especificar' },
    measurementType: { type: String, required: false, default: 'Sin especificar' },
    measurementValue: { type: String, required: false, default: 'Sin especificar' },
    measurementAccuracy: { type: String, required: false, default: 'Sin especificar' },
    measurementUnit: { type: String, required: false, default: 'Sin especificar' },
    measurementDeterminedBy: { type: String, required: false, default: 'Sin especificar' },
    measurementDeterminedDate: { type: String, required: false, default: 'Sin especificar' },
    measurementMethod: { type: String, required: false, default: 'Sin especificar' },
    measurementRemarks: { type: String, required: false, default: 'Sin especificar' },
    // ResourceRelationship
    resourceRelationshipID: { type: String, required: false, default: 'Sin especificar' },
    resourceID: { type: String, required: false, default: 'Sin especificar' },
    relatedResourceID: { type: String, required: false, default: 'Sin especificar' },
    relationshipOfResource: { type: String, required: false, default: 'Sin especificar' },
    relationshipAccordingTo: { type: String, required: false, default: 'Sin especificar' },
    relationshipEstablishedDate: { type: String, required: false, default: 'Sin especificar' },
    relationshipRemarks: { type: String, required: false, default: 'Sin especificar' },
    // Fotografía
    fotografia: { type: Schema.Types.ObjectId, ref: 'Fotografia' }
}, { collection: 'darwinCores' });

module.exports = mongoose.model('DarwinCore', darwinCoreSchema);